### ISSUE TITLE
Download in höchstmögliche MP4 Qualität?

### ISSUE THREAD

**Issue by SirHolgi** [iNaD/download-station-wdrmediathek#4]
Hallo Daniel,

der Download über den Link http://www1.wdr.de/mediathek/video/sendungen/fernsehfilm/video-zwei-bauern-und-kein-land-102.html läd bei mir nicht die höchstmögliche MP4 Qualität herunter.

Infos zur heruntergeladenen Datei:
Dateigröße 201 MB, Auflösung 480*270, Länge 1:28:30

Infos zur Diskstation:
DS412+mit DSM 6.1.1-15101 Update 4

Infos zum Hosting Provider:
wdrmediathek.host 0.2b

Lg
Holger

**Comment by iNaD** [comment]
Da dieses Projekt nicht mehr weitergeführt wird und die neue Implementation überarbeitet wurde, schließe ich dieses Issue hier.

Schaue stattdessen hier vorbei: https://github.com/iNaD/ds-mediatheken
